# Generated by Django 3.1.2 on 2020-11-20 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20201120_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('FIT', 'Health / Fitness'), ('PRO', 'Career'), ('FIN', 'Financial'), ('PERS', 'Personal'), ('SPIR', 'Spiritual'), ('FAM', 'Family')], default='FIT', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='goal',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='purpose',
            field=models.TextField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('NS', 'Not started'), ('IP', 'In Progress'), ('AC', 'Accomplished')], default='NS', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True),
        ),
    ]
