# Generated by Django 3.1.3 on 2020-11-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_auto_20201130_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
