# Generated by Django 3.1.2 on 2020-11-20 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_auto_20201120_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='copied_by',
            field=models.ManyToManyField(blank=True, related_name='users_copies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='copied_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='users_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='support',
            field=models.ManyToManyField(blank=True, related_name='users_support', to=settings.AUTH_USER_MODEL),
        ),
    ]
