# Generated by Django 3.1.3 on 2020-11-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_steps_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(blank=True, choices=[('NS', 'Not started'), ('IP', 'In Progress'), ('AC', 'Accomplished')], max_length=50),
        ),
    ]
