# Generated by Django 3.1.3 on 2020-11-30 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_auto_20201130_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='goals.goalstatus'),
        ),
    ]
