# Generated by Django 3.1.3 on 2020-11-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_auto_20201124_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='copied_times',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
