# Generated by Django 3.1.3 on 2020-12-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_auto_20201130_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
