# Generated by Django 3.1.3 on 2020-12-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_auto_20201202_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_trending',
            field=models.BooleanField(default=True),
        ),
    ]
