# Generated by Django 3.1.3 on 2020-12-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0013_profile_display_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
