# Generated by Django 3.1.3 on 2020-12-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0014_auto_20201207_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='term',
            field=models.CharField(choices=[('FT', 'Fixed Term'), ('LT', 'Life-time')], default=('FT', 'Fixed Term'), max_length=50),
        ),
    ]
